# Generated by Django 5.2.3 on 2025-10-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_savedposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatar/default_avatar.jpg', null=True, upload_to='avatars'),
        ),
    ]
